# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"setup": "90_multi_pyspin.ipynb",
         "init": "90_multi_pyspin.ipynb",
         "deinit": "90_multi_pyspin.ipynb",
         "get_gain": "90_multi_pyspin.ipynb",
         "set_gain": "90_multi_pyspin.ipynb",
         "get_exposure": "90_multi_pyspin.ipynb",
         "set_exposure": "90_multi_pyspin.ipynb",
         "get_frame_rate": "90_multi_pyspin.ipynb",
         "set_frame_rate": "90_multi_pyspin.ipynb",
         "start_acquisition": "90_multi_pyspin.ipynb",
         "end_acquisition": "90_multi_pyspin.ipynb",
         "get_image": "90_multi_pyspin.ipynb",
         "node_cmd": "90_multi_pyspin.ipynb",
         "update_timestamp_offset": "90_multi_pyspin.ipynb",
         "reset_cameras": "90_multi_pyspin.ipynb",
         "register": "92_FLIR_server_utils.ipynb",
         "SERIAL_DICT": "90_multi_pyspin.ipynb",
         "CameraThread": "92_FLIR_server_utils.ipynb",
         "GPIOThread": "92_FLIR_server_utils.ipynb",
         "server": "92_FLIR_server_utils.ipynb",
         "PORT": "93_FLIR_client_utils.ipynb",
         "SHOW_CV_WINDOW": "92_FLIR_server_utils.ipynb",
         "client": "93_FLIR_client_utils.ipynb",
         "stereo_client": "93_FLIR_client_utils.ipynb",
         "width": "93_FLIR_client_utils.ipynb",
         "height": "93_FLIR_client_utils.ipynb"}

modules = ["multi_pyspin.py",
           "FLIR_server_utils.py",
           "FLIR_client_utils.py"]

doc_url = "https://johnnewto.github.io/FLIR_pubsub/"

git_url = "https://github.com/johnnewto/FLIR_pubsub/tree/master/"

def custom_doc_links(name): return None
